
/*
 * Reportes.java
 *
 * Created on 15/09/2010, 07:06:59 PM
 */
package interfaz.reportes;

import BaseDatos.ConexionBase;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author christmo
 */
public class Reportes extends javax.swing.JDialog {

    private ConexionBase bd;
    private String[] sesion;

    public Reportes(JFrame padre, String[] ses, ConexionBase cb) {
        super(padre, "Reportes");
        super.setIconImage(new ImageIcon(getClass().getResource("/interfaz/iconos/kradac_icono.png")).getImage());
        this.sesion = ses;
        this.bd = cb;
        initComponents();
        Configuraciones();
    }

    private void Configuraciones() {
        jdFechaIniDes.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        jdFechaIniDes.setDate(new GregorianCalendar().getTime());
        jdFechaFinDes.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        jdFechaFinDes.setDate(new GregorianCalendar().getTime());
        jpFechasDes.setVisible(false);
        jcMeses.setEnabled(false);
        jcMesesClientes.setEnabled(false);
        jcMesesUnidades.setEnabled(false);
        jcMultasMes.setEnabled(false);
    }

    /**
     * Limpia los campos del tab 0 --> clientes
     */
    private void LimpiarTabClientes() {
        jcTodosClientes.setSelected(false);
        jtCodCli.setText("");
        jtTelCli.setText("");
        jtNomCli.setText("");
    }

    /**
     * Limpia los campos del tab 1 --> clientes
     */
    private void LimpiarTabDespachos() {
        jdFechaIniDes.setDate(new GregorianCalendar().getTime());
        jpFechasDes.setVisible(false);
        rCodCliDes.setSelected(false);
        rUnidadDes.setSelected(false);
        jtCodigoDes.setText("");
        jtUnidadDes.setText("");
    }

    /**
     * Limpia los campos del tab 2 --> carreras
     */
    private void LimpiarCarreras() {
        jcMeses.setEnabled(false);
        jcMesesClientes.setEnabled(false);
        jcMesesUnidades.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgClientes = new javax.swing.ButtonGroup();
        rgDespachos = new javax.swing.ButtonGroup();
        rgCarerras = new javax.swing.ButtonGroup();
        rgMultas = new javax.swing.ButtonGroup();
        rgMultasOpcion = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabReportes = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jcTodosClientes = new javax.swing.JCheckBox();
        jpClientes = new javax.swing.JPanel();
        jtCodCli = new javax.swing.JTextField();
        jtTelCli = new javax.swing.JTextField();
        jtNomCli = new javax.swing.JTextField();
        rCodCli = new javax.swing.JRadioButton();
        rTelCli = new javax.swing.JRadioButton();
        rNomCli = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rUnidadDes = new javax.swing.JRadioButton();
        rCodCliDes = new javax.swing.JRadioButton();
        jtCodigoDes = new javax.swing.JTextField();
        jtUnidadDes = new javax.swing.JTextField();
        rTodasCarrerasPorDia = new javax.swing.JRadioButton();
        jpFechasDes = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jdFechaIniDes = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        jdFechaFinDes = new org.jdesktop.swingx.JXDatePicker();
        jPanel5 = new javax.swing.JPanel();
        jrTotalCarerrasEmpresa = new javax.swing.JRadioButton();
        jrTotalCarrerasEmpresaMes = new javax.swing.JRadioButton();
        jcMeses = new javax.swing.JComboBox();
        jrTotalCarrerasPorCliente = new javax.swing.JRadioButton();
        jrTotalCarrerasClientesMes = new javax.swing.JRadioButton();
        jcMesesClientes = new javax.swing.JComboBox();
        jrTotalCarrerasUnidad = new javax.swing.JRadioButton();
        jrTotalCarrerasUnidadMes = new javax.swing.JRadioButton();
        jcMesesUnidades = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jrMultasAsignadas = new javax.swing.JRadioButton();
        jrMultasPagadas = new javax.swing.JRadioButton();
        jrMultasPorPagar = new javax.swing.JRadioButton();
        jrTiposMultas = new javax.swing.JRadioButton();
        jrMultasTotales = new javax.swing.JRadioButton();
        jrMultasMensuales = new javax.swing.JRadioButton();
        jcMultasMes = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbSalir = new javax.swing.JButton();
        jbGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reportes");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("Generar Reporte de Clientes");

        jcTodosClientes.setText("Todos los Clientes");
        jcTodosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTodosClientesActionPerformed(evt);
            }
        });

        jpClientes.setEnabled(false);

        jtCodCli.setEditable(false);
        jtCodCli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCodCliFocusLost(evt);
            }
        });

        jtTelCli.setEditable(false);
        jtTelCli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtTelCliFocusLost(evt);
            }
        });

        jtNomCli.setEditable(false);
        jtNomCli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomCliFocusLost(evt);
            }
        });

        rgClientes.add(rCodCli);
        rCodCli.setText("Código de cliente:");
        rCodCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCodCliActionPerformed(evt);
            }
        });

        rgClientes.add(rTelCli);
        rTelCli.setText("Teléfono:");
        rTelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTelCliActionPerformed(evt);
            }
        });

        rgClientes.add(rNomCli);
        rNomCli.setText("Nombre del cliente:");
        rNomCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNomCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpClientesLayout = new javax.swing.GroupLayout(jpClientes);
        jpClientes.setLayout(jpClientesLayout);
        jpClientesLayout.setHorizontalGroup(
            jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rCodCli)
                    .addComponent(rTelCli)
                    .addComponent(rNomCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNomCli, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpClientesLayout.setVerticalGroup(
            jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCodCli)
                    .addComponent(jtCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rTelCli)
                    .addComponent(jtTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClientesLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jtNomCli))
                    .addComponent(rNomCli))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcTodosClientes))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcTodosClientes)
                .addGap(18, 18, 18)
                .addComponent(jpClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(123, 123, 123))
        );

        jTabReportes.addTab("Clientes", new javax.swing.ImageIcon(getClass().getResource("/interfaz/iconos/usuario.png")), jPanel1); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rgDespachos.add(rUnidadDes);
        rUnidadDes.setText("Unidad");
        rUnidadDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rUnidadDesActionPerformed(evt);
            }
        });

        rgDespachos.add(rCodCliDes);
        rCodCliDes.setText("Codigo de cliente:");
        rCodCliDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCodCliDesActionPerformed(evt);
            }
        });

        jtCodigoDes.setEditable(false);
        jtCodigoDes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCodigoDesFocusLost(evt);
            }
        });

        jtUnidadDes.setEditable(false);
        jtUnidadDes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtUnidadDesFocusLost(evt);
            }
        });

        rgDespachos.add(rTodasCarrerasPorDia);
        rTodasCarrerasPorDia.setText("Todas las carreras de un día");
        rTodasCarrerasPorDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTodasCarrerasPorDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rCodCliDes)
                            .addComponent(rUnidadDes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtCodigoDes, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                            .addComponent(jtUnidadDes, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)))
                    .addComponent(rTodasCarrerasPorDia))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rUnidadDes)
                    .addComponent(jtUnidadDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCodCliDes)
                    .addComponent(jtCodigoDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(rTodasCarrerasPorDia)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Fechas"));

        jLabel2.setText("Inicio:");

        jLabel5.setText("Fin:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdFechaIniDes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdFechaFinDes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jdFechaIniDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jdFechaFinDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpFechasDesLayout = new javax.swing.GroupLayout(jpFechasDes);
        jpFechasDes.setLayout(jpFechasDesLayout);
        jpFechasDesLayout.setHorizontalGroup(
            jpFechasDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFechasDesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpFechasDesLayout.setVerticalGroup(
            jpFechasDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFechasDesLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpFechasDes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpFechasDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabReportes.addTab("Despachos", new javax.swing.ImageIcon(getClass().getResource("/interfaz/iconos/vehiculo.png")), jPanel2); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rgCarerras.add(jrTotalCarerrasEmpresa);
        jrTotalCarerrasEmpresa.setText("Total de carreras de la empresa");
        jrTotalCarerrasEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrTotalCarerrasEmpresaActionPerformed(evt);
            }
        });

        rgCarerras.add(jrTotalCarrerasEmpresaMes);
        jrTotalCarrerasEmpresaMes.setText("Total de carreras mensual:");
        jrTotalCarrerasEmpresaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrTotalCarrerasEmpresaMesActionPerformed(evt);
            }
        });

        jcMeses.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        rgCarerras.add(jrTotalCarrerasPorCliente);
        jrTotalCarrerasPorCliente.setText("Total de carreras de clientes");
        jrTotalCarrerasPorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrTotalCarrerasPorClienteActionPerformed(evt);
            }
        });

        rgCarerras.add(jrTotalCarrerasClientesMes);
        jrTotalCarrerasClientesMes.setText("Total de carreras de clientes por mes:");
        jrTotalCarrerasClientesMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrTotalCarrerasClientesMesActionPerformed(evt);
            }
        });

        jcMesesClientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        rgCarerras.add(jrTotalCarrerasUnidad);
        jrTotalCarrerasUnidad.setText("Total de carreras por unidad");
        jrTotalCarrerasUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrTotalCarrerasUnidadActionPerformed(evt);
            }
        });

        rgCarerras.add(jrTotalCarrerasUnidadMes);
        jrTotalCarrerasUnidadMes.setText("Total de carreras de unidades por mes:");
        jrTotalCarrerasUnidadMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrTotalCarrerasUnidadMesActionPerformed(evt);
            }
        });

        jcMesesUnidades.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrTotalCarerrasEmpresa)
                    .addComponent(jrTotalCarrerasPorCliente)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jrTotalCarrerasEmpresaMes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jrTotalCarrerasClientesMes)
                            .addGap(18, 18, 18)
                            .addComponent(jcMesesClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jrTotalCarrerasUnidad)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jrTotalCarrerasUnidadMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcMesesUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrTotalCarerrasEmpresa)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrTotalCarrerasEmpresaMes)
                    .addComponent(jcMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jrTotalCarrerasPorCliente)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrTotalCarrerasClientesMes)
                    .addComponent(jcMesesClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jrTotalCarrerasUnidad)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrTotalCarrerasUnidadMes)
                    .addComponent(jcMesesUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabReportes.addTab("Carreras", new javax.swing.ImageIcon(getClass().getResource("/interfaz/iconos/carreras.png")), jPanel5); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rgMultas.add(jrMultasAsignadas);
        jrMultasAsignadas.setText("Multas Asignadas");
        jrMultasAsignadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMultasAsignadasActionPerformed(evt);
            }
        });

        rgMultas.add(jrMultasPagadas);
        jrMultasPagadas.setText("Multas Pagadas");
        jrMultasPagadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMultasPagadasActionPerformed(evt);
            }
        });

        rgMultas.add(jrMultasPorPagar);
        jrMultasPorPagar.setText("Multas por pagar");
        jrMultasPorPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMultasPorPagarActionPerformed(evt);
            }
        });

        rgMultas.add(jrTiposMultas);
        jrTiposMultas.setText("Tipos de Multas");
        jrTiposMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrTiposMultasActionPerformed(evt);
            }
        });

        rgMultasOpcion.add(jrMultasTotales);
        jrMultasTotales.setSelected(true);
        jrMultasTotales.setText("Total");
        jrMultasTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMultasTotalesActionPerformed(evt);
            }
        });

        rgMultasOpcion.add(jrMultasMensuales);
        jrMultasMensuales.setText("Mensual");
        jrMultasMensuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMultasMensualesActionPerformed(evt);
            }
        });

        jcMultasMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel3.setText("Seleccionar el tipo de reporte que se quiere obtener:");

        jLabel4.setText("Seleccionar el tipo de reporte que desee:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jrMultasAsignadas)
                        .addGap(18, 18, 18)
                        .addComponent(jrMultasPagadas)
                        .addGap(18, 18, 18)
                        .addComponent(jrMultasPorPagar))
                    .addComponent(jrTiposMultas)
                    .addComponent(jrMultasTotales)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jrMultasMensuales)
                        .addGap(18, 18, 18)
                        .addComponent(jcMultasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrTiposMultas)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrMultasAsignadas)
                    .addComponent(jrMultasPagadas)
                    .addComponent(jrMultasPorPagar))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrMultasTotales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrMultasMensuales)
                    .addComponent(jcMultasMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabReportes.addTab("Multas", new javax.swing.ImageIcon(getClass().getResource("/interfaz/iconos/police.png")), jPanel6); // NOI18N

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/iconos/salir.png"))); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/iconos/reporte.png"))); // NOI18N
        jbGenerar.setText("Generar");
        jbGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                        .addComponent(jbGenerar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir)
                    .addComponent(jbGenerar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcTodosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTodosClientesActionPerformed
        if (jcTodosClientes.isSelected()) {
            jpClientes.setVisible(false);
        } else {
            jpClientes.setVisible(true);
            LimpiarTabClientes();
        }
    }//GEN-LAST:event_jcTodosClientesActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarActionPerformed
        System.out.println(jTabReportes.getSelectedIndex());
        int idx = jTabReportes.getSelectedIndex();
        GenerarReporte(idx);
    }//GEN-LAST:event_jbGenerarActionPerformed

    private void jtCodCliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCodCliFocusLost
        if (!jtCodCli.equals("")) {
            try {
                Integer.parseInt(jtCodCli.getText());
            } catch (NumberFormatException ex) {
                jtCodCli.setText("");
                JOptionPane.showMessageDialog(this, "Solo se puede ingresar numeros...", "Error...", 0);
            }
        }
    }//GEN-LAST:event_jtCodCliFocusLost

    private void jtTelCliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTelCliFocusLost
        if (!jtTelCli.equals("")) {
            try {
                Integer.parseInt(jtTelCli.getText());
            } catch (NumberFormatException ex) {
                jtTelCli.setText("");
                JOptionPane.showMessageDialog(this, "Solo se puede ingresar numeros...", "Error...", 0);
            }
        }
    }//GEN-LAST:event_jtTelCliFocusLost

    private void jtNomCliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomCliFocusLost
        jtNomCli.setText(jtNomCli.getText().toUpperCase());
    }//GEN-LAST:event_jtNomCliFocusLost

    private void rCodCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCodCliActionPerformed
        LimpiarTabClientes();
        if (rCodCli.isSelected()) {
            jtCodCli.setEditable(true);
            jtTelCli.setEditable(false);
            jtNomCli.setEditable(false);
        } else {
            jtCodCli.setEditable(false);
        }
    }//GEN-LAST:event_rCodCliActionPerformed

    private void rTelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTelCliActionPerformed
        LimpiarTabClientes();
        if (rTelCli.isSelected()) {
            jtTelCli.setEditable(true);
            jtCodCli.setEditable(false);
            jtNomCli.setEditable(false);
        } else {
            jtTelCli.setEditable(false);
        }
    }//GEN-LAST:event_rTelCliActionPerformed

    private void rNomCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNomCliActionPerformed
        LimpiarTabClientes();
        if (rNomCli.isSelected()) {
            jtNomCli.setEditable(true);
            jtTelCli.setEditable(false);
            jtCodCli.setEditable(false);
        } else {
            jtNomCli.setEditable(false);
        }
    }//GEN-LAST:event_rNomCliActionPerformed

    private void rUnidadDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rUnidadDesActionPerformed
        LimpiarTabDespachos();
        if (rUnidadDes.isSelected()) {
            jtUnidadDes.setEditable(true);
            jtCodigoDes.setEditable(false);
            jpFechasDes.setVisible(true);
        } else {
            jtUnidadDes.setEnabled(false);
        }
    }//GEN-LAST:event_rUnidadDesActionPerformed

    private void rCodCliDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCodCliDesActionPerformed
        LimpiarTabDespachos();
        if (rCodCliDes.isSelected()) {
            jtCodigoDes.setEditable(true);
            jtUnidadDes.setEditable(false);
            jpFechasDes.setVisible(true);
        } else {
            jtCodigoDes.setEnabled(false);
        }
    }//GEN-LAST:event_rCodCliDesActionPerformed

    private void jtUnidadDesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtUnidadDesFocusLost
        try {
            Integer.parseInt(jtUnidadDes.getText());
            jtCodigoDes.setText("");
        } catch (NumberFormatException ex) {
            jtUnidadDes.setText("");
            JOptionPane.showMessageDialog(this, "Solo se puede ingresar numeros...", "Error...", 0);
        }
    }//GEN-LAST:event_jtUnidadDesFocusLost

    private void jtCodigoDesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCodigoDesFocusLost
        try {
            Integer.parseInt(jtCodigoDes.getText());
            jtUnidadDes.setText("");
        } catch (NumberFormatException ex) {
            jtCodigoDes.setText("");
            JOptionPane.showMessageDialog(this, "Solo se puede ingresar numeros...", "Error...", 0);
        }
    }//GEN-LAST:event_jtCodigoDesFocusLost

    private void rTodasCarrerasPorDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTodasCarrerasPorDiaActionPerformed
        if (rTodasCarrerasPorDia.isSelected()) {
            jpFechasDes.setVisible(true);
            jtCodigoDes.setEditable(false);
            jtUnidadDes.setEditable(false);
        }
    }//GEN-LAST:event_rTodasCarrerasPorDiaActionPerformed

    private void jrTotalCarerrasEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrTotalCarerrasEmpresaActionPerformed
        LimpiarCarreras();
    }//GEN-LAST:event_jrTotalCarerrasEmpresaActionPerformed

    private void jrTotalCarrerasEmpresaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrTotalCarrerasEmpresaMesActionPerformed
        LimpiarCarreras();
        jcMeses.setEnabled(true);
    }//GEN-LAST:event_jrTotalCarrerasEmpresaMesActionPerformed

    private void jrTotalCarrerasPorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrTotalCarrerasPorClienteActionPerformed
        LimpiarCarreras();
    }//GEN-LAST:event_jrTotalCarrerasPorClienteActionPerformed

    private void jrTotalCarrerasClientesMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrTotalCarrerasClientesMesActionPerformed
        LimpiarCarreras();
        jcMesesClientes.setEnabled(true);
    }//GEN-LAST:event_jrTotalCarrerasClientesMesActionPerformed

    private void jrTotalCarrerasUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrTotalCarrerasUnidadActionPerformed
        LimpiarCarreras();
    }//GEN-LAST:event_jrTotalCarrerasUnidadActionPerformed

    private void jrTotalCarrerasUnidadMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrTotalCarrerasUnidadMesActionPerformed
        LimpiarCarreras();
        jcMesesUnidades.setEnabled(true);
    }//GEN-LAST:event_jrTotalCarrerasUnidadMesActionPerformed

    private void jrMultasMensualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMultasMensualesActionPerformed
        jcMultasMes.setEnabled(true);
    }//GEN-LAST:event_jrMultasMensualesActionPerformed

    private void jrMultasTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMultasTotalesActionPerformed
        jcMultasMes.setEnabled(false);
    }//GEN-LAST:event_jrMultasTotalesActionPerformed

    private void jrTiposMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrTiposMultasActionPerformed
        OpcionMultasReporte(false);
    }//GEN-LAST:event_jrTiposMultasActionPerformed

    private void jrMultasAsignadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMultasAsignadasActionPerformed
        OpcionMultasReporte(true);
    }//GEN-LAST:event_jrMultasAsignadasActionPerformed

    private void jrMultasPagadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMultasPagadasActionPerformed
        OpcionMultasReporte(true);
    }//GEN-LAST:event_jrMultasPagadasActionPerformed

    private void jrMultasPorPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMultasPorPagarActionPerformed
        OpcionMultasReporte(true);
    }//GEN-LAST:event_jrMultasPorPagarActionPerformed

    /**
     * Habilita o deshabilita las opciones de totales o mensuales
     * @param b
     */
    private void OpcionMultasReporte(boolean b) {
        jrMultasTotales.setEnabled(b);
        jrMultasMensuales.setEnabled(b);
        if (jrTiposMultas.isSelected()) {
            jcMultasMes.setEnabled(b);
        }
    }

    /**
     * Retorna el valor de las cajas de texto de clientes para enviarlas a generar
     * el reporte...
     * @return HashMap
     */
    private HashMap getDatosCliente() {
        HashMap map = new HashMap();
        if (!jcTodosClientes.isSelected()) {
            String cod = jtCodCli.getText();
            String tel = jtTelCli.getText();
            String nom = jtNomCli.getText();
            map.put("cod", cod);
            map.put("tel", tel);
            map.put("nom", nom);
            map.put("todo", false);
        } else {
            map.put("todo", true);
        }
        return map;
    }

    /**
     * Obtiene los datos del formulario de despachos para generar el reporte
     * @return HashMap 
     */
    private HashMap getDatosDespacho() {
        HashMap map = new HashMap();

        String cod = jtCodigoDes.getText();
        String uni = jtUnidadDes.getText();

        SimpleDateFormat dfFecha = new SimpleDateFormat("yyyy-MM-dd");

        String fechaIni = dfFecha.format(jdFechaIniDes.getDate());
        String fechaFin = dfFecha.format(jdFechaFinDes.getDate());

        map.put("cod", cod);
        map.put("uni", uni);
        map.put("fechaIni", fechaIni);
        map.put("fechaFin", fechaFin);
        if (rTodasCarrerasPorDia.isSelected()) {
            map.put("todo", true);
        } else {
            map.put("todo", false);
        }

        return map;
    }

    /**
     * Obtiene los datos del formulario de Carreras para generar el reporte
     * @return HashMap
     */
    private HashMap getDatosCarreras() {
        HashMap map = new HashMap();

        if (jrTotalCarerrasEmpresa.isSelected()
                || jrTotalCarrerasPorCliente.isSelected()
                || jrTotalCarrerasUnidad.isSelected()) {
            map.put("todo", true);
        } else {
            map.put("todo", false);
            /**
             * Datos de la empresa
             */
            String mesEmp = "" + (jcMeses.getSelectedIndex() + 1);
            String nomMesEmp = jcMeses.getSelectedItem().toString();
            map.put("mes", mesEmp);
            map.put("NombreMes", nomMesEmp);
            /**
             * Datos de los clientes
             */
            String mesCli = "" + (jcMesesClientes.getSelectedIndex() + 1);
            String nomMesCli = jcMesesClientes.getSelectedItem().toString();
            map.put("mesCli", mesCli);
            map.put("NombreMesCli", nomMesCli);
            /**
             * Datos de las unidades
             */
            String mesUni = "" + (jcMesesUnidades.getSelectedIndex() + 1);
            String nomMesUni = jcMesesUnidades.getSelectedItem().toString();
            map.put("mesUni", mesUni);
            map.put("NombreMesUni", nomMesUni);
        }

        if (jrTotalCarrerasPorCliente.isSelected() || jrTotalCarrerasClientesMes.isSelected()) {
            map.put("radio", "cliente");
        } else if (jrTotalCarerrasEmpresa.isSelected() || jrTotalCarrerasEmpresaMes.isSelected()) {
            map.put("radio", "empresa");
        } else if (jrTotalCarrerasUnidad.isSelected() || jrTotalCarrerasUnidadMes.isSelected()) {
            map.put("radio", "unidad");
        }

        return map;
    }

    /**
     * Obtiene los datos del formulario de reportes de la seccion de multas para
     * enviar a generar el reporte
     * @return HashMap
     */
    private HashMap getDatosMultas() {
        HashMap map = new HashMap();

        if (jrTiposMultas.isSelected()) {
            map.put("cat", "tiposMultas");
        } else if (jrMultasAsignadas.isSelected()) {
            map.put("cat", "asignadas");
        } else if (jrMultasPagadas.isSelected()) {
            map.put("cat", "pagadas");
        } else if (jrMultasPorPagar.isSelected()) {
            map.put("cat", "porPagar");
        }


        if (jrMultasTotales.isSelected()) {
            map.put("op", "total");
        } else if (jrMultasMensuales.isSelected()) {
            map.put("op", "mensual");
        }

        String mes = "" + (jcMultasMes.getSelectedIndex() + 1);
        String nomMes = jcMultasMes.getSelectedItem().toString();
        map.put("mes", mes);
        map.put("NombreMes", nomMes);

        return map;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabReportes;
    private javax.swing.JButton jbGenerar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox jcMeses;
    private javax.swing.JComboBox jcMesesClientes;
    private javax.swing.JComboBox jcMesesUnidades;
    private javax.swing.JComboBox jcMultasMes;
    private javax.swing.JCheckBox jcTodosClientes;
    private org.jdesktop.swingx.JXDatePicker jdFechaFinDes;
    private org.jdesktop.swingx.JXDatePicker jdFechaIniDes;
    private javax.swing.JPanel jpClientes;
    private javax.swing.JPanel jpFechasDes;
    private javax.swing.JRadioButton jrMultasAsignadas;
    private javax.swing.JRadioButton jrMultasMensuales;
    private javax.swing.JRadioButton jrMultasPagadas;
    private javax.swing.JRadioButton jrMultasPorPagar;
    private javax.swing.JRadioButton jrMultasTotales;
    private javax.swing.JRadioButton jrTiposMultas;
    private javax.swing.JRadioButton jrTotalCarerrasEmpresa;
    private javax.swing.JRadioButton jrTotalCarrerasClientesMes;
    private javax.swing.JRadioButton jrTotalCarrerasEmpresaMes;
    private javax.swing.JRadioButton jrTotalCarrerasPorCliente;
    private javax.swing.JRadioButton jrTotalCarrerasUnidad;
    private javax.swing.JRadioButton jrTotalCarrerasUnidadMes;
    private javax.swing.JTextField jtCodCli;
    private javax.swing.JTextField jtCodigoDes;
    private javax.swing.JTextField jtNomCli;
    private javax.swing.JTextField jtTelCli;
    private javax.swing.JTextField jtUnidadDes;
    private javax.swing.JRadioButton rCodCli;
    private javax.swing.JRadioButton rCodCliDes;
    private javax.swing.JRadioButton rNomCli;
    private javax.swing.JRadioButton rTelCli;
    private javax.swing.JRadioButton rTodasCarrerasPorDia;
    private javax.swing.JRadioButton rUnidadDes;
    private javax.swing.ButtonGroup rgCarerras;
    private javax.swing.ButtonGroup rgClientes;
    private javax.swing.ButtonGroup rgDespachos;
    private javax.swing.ButtonGroup rgMultas;
    private javax.swing.ButtonGroup rgMultasOpcion;
    // End of variables declaration//GEN-END:variables

    /**
     * Genera los reportes para cada uno de los tabs que haya en este diseñado
     * en este frame
     * @param idx
     */
    private void GenerarReporte(int idx) {
        switch (idx) {
            case 0:
                GenerarReporteClientes clientes = new GenerarReporteClientes(bd, getDatosCliente(), sesion);
                clientes.Generar();
                break;
            case 1:
                GenerarReporteDespachos despachos = new GenerarReporteDespachos(bd, getDatosDespacho(), sesion);
                despachos.Generar();
                break;
            case 2:
                GenerarReporteCarreras carreras = new GenerarReporteCarreras(bd, getDatosCarreras(), sesion);
                carreras.Generar();
                break;
            case 3:
                GenerarReporteMultas multas = new GenerarReporteMultas(bd, getDatosMultas(), sesion);
                multas.Generar();
        }
    }
}
