/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaMail.java
 *
 * Created on 31/08/2010, 02:21:59 PM
 */
package interfaz.comunicacion.mail;

import BaseDatos.ConexionBase;
import java.util.ResourceBundle;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class VentanaMail extends javax.swing.JDialog {

    private ConexionBase bd;
    private String[] sesion;
    private String empresa;

    /** Creates new form VentanaMail */
    public VentanaMail() {
        initComponents();
    }

    public VentanaMail(ConexionBase base, String[] sesion) {
        initComponents();
        this.bd = base;
        this.sesion = sesion;
        this.empresa = bd.getEmpresa(sesion[1]);
        jxBusy.setVisible(false);
        jxBusy.setBusy(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtMensaje = new javax.swing.JTextArea();
        jbEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbLimpiar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jxBusy = new org.jdesktop.swingx.JXBusyLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte de Problemas");
        setAlwaysOnTop(true);
        setResizable(false);

        jtMensaje.setColumns(20);
        jtMensaje.setLineWrap(true);
        jtMensaje.setRows(15);
        jtMensaje.setTabSize(0);
        jtMensaje.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(jtMensaje);

        jbEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/iconos/email.png"))); // NOI18N
        jbEnviar.setText("Enviar");
        jbEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbEnviarMousePressed(evt);
            }
        });
        jbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reportar Problemas");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("<html>Mediante este medio, usted nos puede informar sobre problemas o requerimientos que tenga para <br/>enriquecer el sistema de monitoreo y despachos...</html>");
        jLabel2.setAlignmentX(5.0F);
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/iconos/limpiar.png"))); // NOI18N
        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/iconos/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Se enviará el mensaje a: soporte@kradac.com");

        jxBusy.setText("Enviando Mensaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jxBusy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jxBusy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        jtMensaje.setText("");
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarActionPerformed
        String msg = jtMensaje.getText();
        if (!msg.equals("")) {
            enviaMail(msg);
        } else {
            jxBusy.setVisible(false);
            JOptionPane.showMessageDialog(this, "No se puede enviar mensaje en blanco...", "Error...", 0);
        }
    }//GEN-LAST:event_jbEnviarActionPerformed

    private void jbEnviarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEnviarMousePressed
        jxBusy.setVisible(true);
    }//GEN-LAST:event_jbEnviarMousePressed

    /**
     * Enviar mensaje a soporte kradac
     * @param msg
     */
    private void enviaMail(String msg) {
        jxBusy.setVisible(false);
        jxBusy.setBusy(false);
        String titulo = "Empresa: " + bd.getEmpresa(sesion[1]) + " Usuario: " + sesion[2];
        StringBuilder mensaje = new StringBuilder();
        mensaje.append("Reporte de problemas del sistema:<br/>");
        mensaje.append("<br/>Empresa: ").append(empresa);
        mensaje.append("<br/>Usuario: ").append(sesion[2]);
        mensaje.append("<br/>Teléfono: ").append(bd.getTelefonoUsuario(sesion[0]));

        mensaje.append("<br/><br/>Mensaje:<br/><br/>");
        mensaje.append(procesarMensaje(msg));
        mensaje.append("<br/><br/>-------------<br/><br/>");

        ResourceBundle props = ResourceBundle.getBundle("interfaz.comunicacion.mail.smtp");
        boolean envio = SMTPConfig.sendMail(titulo, mensaje.toString(), props.getString("mail.user"));

        if (envio) {
            Icon ic = new ImageIcon(getClass().getResource("/interfaz/iconos/correcto.png"));
            JOptionPane.showMessageDialog(this, "Mensaje enviado correctamente...\n"
                    + "Sus requerimientos seran evaluados, el equipo de soporte KRADAC le enformará sobre los resultados...",
                    "Mensaje", 1, ic);
            this.dispose();
        } else {
            jxBusy.setVisible(false);
            JOptionPane.showMessageDialog(this, "Su mensaje no pudo ser enviado:\n\n"
                    + "Posibles razones:\n"
                    + "\n1. No cuenta actualmente con interenet en su equipo."
                    + "\n2. El cable de red puede estar desconectado."
                    + "\n3. La configuración del equipo tiene problemas.\n\n"
                    + "Al revisar los dos primeros punto ud continua con problemas, contacte con el equipo de soporte KRADAC\n"
                    + "al e-mail soporte@kradac.com o de forma teléfonica, para que se pueda solucionar este inconveniente.",
                    "Error...", 0);
            this.dispose();
        }
    }

    /**
     * procesa el mensaje para enviar el mail
     * reemplaza el \n por un <br/>
     * @param msg
     * @return String
     */
    private String procesarMensaje(String msg) {
        String st = "";
        byte[] bte = msg.getBytes();
        for (int i = 0; i < msg.getBytes().length; i++) {
            if (bte[i] != 10) {
                st += msg.charAt(i);
            } else {
                st += "<br/>";
            }
        }
        return st;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEnviar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JTextArea jtMensaje;
    private org.jdesktop.swingx.JXBusyLabel jxBusy;
    // End of variables declaration//GEN-END:variables
}
