
/*
 * VentanaDatos.java
 *
 * Created on 05/08/2010, 09:57:11 AM
 */
package interfaz.subVentanas;

import BaseDatos.ConexionBase;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author root
 */
public class VentanaDatos extends javax.swing.JFrame {

    private Despachos datos = new Despachos();
    private ConexionBase bd = new ConexionBase();
    private boolean accion = false;
    private ResultSet rs;
    private int filaSeleccionada;
    private JTable tabla;

    /** Creates new form VentanaDatos */
    public VentanaDatos() {
        initComponents();
        //VentanaDatos.main(null);
    }

    public VentanaDatos(Despachos despacho) {
        initComponents();
        this.datos = despacho;
        cargarDatos(datos);
    }

    public void setDatosFila(JTable tabla, int fila) {
        this.filaSeleccionada = fila;
        this.tabla = tabla;
    }

    /**
     * Carga cada uno de los Datos en los cuadros de texto
     * @param despacho
     */
    private void cargarDatos(Despachos despacho) {
        String cod = despacho.getStrCodigo();
        if (cod == null || cod.equals("")) {
            jbCodigo.setVisible(true);
            accion = true; //insertar
        } else {
            jbCodigo.setVisible(false);
            accion = false; //actualizar
        }
        jtCodigo.setText(cod);
        jtTelefono.setText(despacho.getStrTelefono());
        jtNombre.setText(despacho.getStrNombre());
        jtDireccion.setText(despacho.getStrDireccion());
        jtBarrio.setText(despacho.getStrBarrio());
        jtNota.setText(despacho.getStrNota());
        String sql = "SELECT NUM_CASA_CLI, INFOR_ADICIONAL,LATITUD,LONGITUD FROM CLIENTES WHERE CODIGO='" + despacho.getStrCodigo() + "'";
        rs = bd.ejecutarConsultaUnDato(sql);
        try {
            String n_casa = rs.getString("NUM_CASA_CLI");
            String referencia = rs.getString("INFOR_ADICIONAL");
            String lat = rs.getString("LATITUD");
            String lon = rs.getString("LONGITUD");
            jtNumeroCasa.setText(n_casa);
            jtReferencia.setText(referencia);
            jtLatitud.setText(lat);
            jtLongitud.setText(lon);
        } catch (SQLException ex) {
            System.err.println("No hay datos en el resulSet... Clase -> VentanaDatos.java :-)");
            //Logger.getLogger(VentanaDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Limpia todos los campos
     */
    public void LimpiarCampos() {
        jtCodigo.setText("");
        jtTelefono.setText("");
        jtNombre.setText("");
        jtDireccion.setText("");
        jtBarrio.setText("");
        jtNota.setText("");
        jtNumeroCasa.setText("");
        jtReferencia.setText("");
        jtLatitud.setText("");
        jtLongitud.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jbAceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtTelefono = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtDireccion = new javax.swing.JTextField();
        jtNumeroCasa = new javax.swing.JTextField();
        jtBarrio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtLatitud = new javax.swing.JTextField();
        jtLongitud = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtReferencia = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtNota = new javax.swing.JTextArea();
        jbCodigo = new javax.swing.JButton();

        jLabel1.setText("Código:");

        jtCodigo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtCodigo.setEnabled(false);

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Dirección:");

        jLabel4.setText("# Casa:");

        jLabel6.setText("Teléfono:");

        jLabel9.setText("Barrio:");

        jtTelefono.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtTelefono.setEnabled(false);

        jtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNombreFocusLost(evt);
            }
        });

        jtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtDireccionFocusLost(evt);
            }
        });

        jtNumeroCasa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNumeroCasaFocusLost(evt);
            }
        });

        jtBarrio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtBarrioFocusLost(evt);
            }
        });

        jLabel7.setText("Latitud:");

        jLabel8.setText("Longitud:");

        jtLatitud.setText("0.0");

        jtLongitud.setText("0.0");

        jLabel5.setText("Referencia:");

        jtReferencia.setColumns(20);
        jtReferencia.setRows(5);
        jtReferencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtReferenciaFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jtReferencia);

        jLabel11.setText("Nota:");

        jtNota.setColumns(20);
        jtNota.setRows(5);
        jtNota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNotaFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(jtNota);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addContainerGap(495, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
        );

        jbCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/iconos/codigo.png"))); // NOI18N
        jbCodigo.setToolTipText("Generar Código");
        jbCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosLayout.createSequentialGroup()
                                .addComponent(jtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(jtNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addComponent(jtLatitud, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jbAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addGap(246, 246, 246))
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAceptar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-600)/2, (screenSize.height-400)/2, 600, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        GuardarDatos();
        bd.CerrarConexion();
        LimpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_jbAceptarActionPerformed

    /**
     * Guarda los datos de nuevos o editados del cliente en la base de datos
     */
    private void GuardarDatos() {
        boolean resultado = false;
        datos = getDatosNuevos();
        if (accion) {
            resultado = bd.InsertarCliente(datos);
            if (!resultado) {
                JOptionPane.showMessageDialog(this, "No se pudo guardar el cliente...", "Error", 0);
            }
        } else {
            resultado = bd.ActualziarCliente(datos, Integer.parseInt(datos.getStrCodigo()));
            if (!resultado) {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el cliente...", "Error", 0);
            }
        }
    }

    /**
     * Inserta la cambios en la tabla de datos por despachar de la interfaz principal
     * @param nota
     */
    private void insertarDatosTabla(String txt,int col) {
        if (!txt.equals("")) {
            tabla.setValueAt(txt, filaSeleccionada, col);
        }
    }

    /**
     * Obtiene los datos nuevos o editados del formulario
     * @return Despachos
     */
    private Despachos getDatosNuevos() {
        Despachos d = new Despachos();
        try {
            d.setStrCodigo(jtCodigo.getText());
            d.setStrTelefono(jtTelefono.getText());
            d.setStrNombre(jtNombre.getText());
            d.setStrDireccion(jtDireccion.getText());
            d.setStrBarrio(jtBarrio.getText());
            d.setStrNota(jtNota.getText());
            d.setStrNumeroCasa(jtNumeroCasa.getText());
            d.setStrReferecia(jtReferencia.getText());
            try {
                d.setLatitud(Double.parseDouble(jtLatitud.getText()));
                d.setLongitud(Double.parseDouble(jtLongitud.getText()));
            } catch (NumberFormatException ex) {
                d.setLatitud(0);
                d.setLongitud(0);
                System.err.println("Latitud o longitud mal");
            }
        } catch (NullPointerException ex) {
            System.err.println("Null en la ventana de Datos");
        }
        return d;
    }

    private void jbCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCodigoActionPerformed
        if (jtCodigo.getText() == null || jtCodigo.getText().equals("")) {
            try {
                int cod = Integer.parseInt(bd.generarCodigo()) + 1;
                jtCodigo.setText("" + cod);
                insertarDatosTabla(jtCodigo.getText(),2);
            } catch (SQLException ex) {
                Logger.getLogger(VentanaDatos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbCodigoActionPerformed

    private void jtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombreFocusLost
        jtNombre.setText(Mayusculas(jtNombre.getText()));
        insertarDatosTabla(jtNombre.getText(),3);
    }//GEN-LAST:event_jtNombreFocusLost

    private void jtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDireccionFocusLost
        jtDireccion.setText(Mayusculas(jtDireccion.getText()));
        insertarDatosTabla(jtDireccion.getText(),4);
    }//GEN-LAST:event_jtDireccionFocusLost

    private void jtBarrioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtBarrioFocusLost
        jtBarrio.setText(Mayusculas(jtBarrio.getText()));
        insertarDatosTabla(jtBarrio.getText(),5);
    }//GEN-LAST:event_jtBarrioFocusLost

    private void jtNumeroCasaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumeroCasaFocusLost
        jtNumeroCasa.setText(Mayusculas(jtNumeroCasa.getText()));
    }//GEN-LAST:event_jtNumeroCasaFocusLost

    private void jtReferenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtReferenciaFocusLost
        jtReferencia.setText(Mayusculas(jtReferencia.getText()));
    }//GEN-LAST:event_jtReferenciaFocusLost

    private void jtNotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNotaFocusLost
        jtNota.setText(Mayusculas(jtNota.getText()));
        insertarDatosTabla(jtNota.getText(),9);
    }//GEN-LAST:event_jtNotaFocusLost

    /**
     * Convierete a mayusculas lo que se envie
     * @param txt
     * @return string
     */
    public String Mayusculas(String txt) {
        return txt.toUpperCase();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VentanaDatos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCodigo;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JTextField jtBarrio;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtDireccion;
    private javax.swing.JTextField jtLatitud;
    private javax.swing.JTextField jtLongitud;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextArea jtNota;
    private javax.swing.JTextField jtNumeroCasa;
    private javax.swing.JTextArea jtReferencia;
    private javax.swing.JTextField jtTelefono;
    // End of variables declaration//GEN-END:variables
}
