/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * INICIO.java
 *
 * Created on 09/08/2010, 04:04:21 PM
 */
package interfaz.pruebas;

/**
 *
 * @author Usuario
 */
public class INICIO extends javax.swing.JFrame {

    /** Creates new form INICIO */
    public INICIO() {
        initComponents();

        btnNvConductor.setText("<html>NUEVO<br>CONDUCTOR</html>");
        

        btnNvUsuario.setText("<html>NUEVO<br>USUARIO</html>");
        btnEditConductor.setText("<html>BUSCAR / EDITAR<br>CONDUCTOR</html>");
        btnBuscarUsuario.setText("<html>BUSCAR / EDITAR<br>USUARIO</html>");
        btnEstados.setText("<html>ESTADOS<br>TAXI</html>");
        btnDespacho.setText("<html>DESPACHO <BR> TAXIS</html>");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNvConductor = new javax.swing.JButton();
        btnEstados = new javax.swing.JButton();
        btnNvUsuario = new javax.swing.JButton();
        btnDespacho = new javax.swing.JButton();
        btnBuscarUsuario = new javax.swing.JButton();
        btnTurnos = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnDirector = new javax.swing.JButton();
        btnEditConductor = new javax.swing.JButton();
        btnDirector1 = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNvConductor.setText("NUEVO CONDUCTOR");
        getContentPane().add(btnNvConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, 85));

        btnEstados.setText("ESTADOS DEL TAXI");
        btnEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 110, 85));

        btnNvUsuario.setText("NUEVO USUARIO");
        getContentPane().add(btnNvUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 110, 85));

        btnDespacho.setText("DESPACHO TAXIS");
        btnDespacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespachoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDespacho, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 110, 85));

        btnBuscarUsuario.setText("BUSCAR / EDITAR USUARIOS");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 110, 85));

        btnTurnos.setText("TURNOS");
        btnTurnos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnTurnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 110, 85));

        btnReportes.setText("REPORTES");
        getContentPane().add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 110, 85));

        btnDirector.setText("AYUDA");
        btnDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectorActionPerformed(evt);
            }
        });
        getContentPane().add(btnDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 110, 50));

        btnEditConductor.setText("BUSCAR / EDITAR  CONDUCTOR");
        btnEditConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditConductorActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 110, 85));

        btnDirector1.setText("DIRECTORIO");
        btnDirector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirector1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDirector1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 110, 85));

        btnConfig.setText("CONFIG");
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 110, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDirectorActionPerformed

    private void btnDespachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespachoActionPerformed

    }//GEN-LAST:event_btnDespachoActionPerformed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btnEditConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditConductorActionPerformed

    private void btnEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstadosActionPerformed

    private void btnDirector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirector1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDirector1ActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new INICIO().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnDespacho;
    private javax.swing.JButton btnDirector;
    private javax.swing.JButton btnDirector1;
    private javax.swing.JButton btnEditConductor;
    private javax.swing.JButton btnEstados;
    private javax.swing.JButton btnNvConductor;
    private javax.swing.JButton btnNvUsuario;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnTurnos;
    // End of variables declaration//GEN-END:variables
}
